[project]
name = "stakeflow"
description = "StakeFlow - NFT staking platform on Stacks"
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.sip-010-trait]
path = "contracts/sip-010-trait.clar"
clarity_version = 2
epoch = 2.5

[contracts.sip-009-trait]
path = "contracts/sip-009-trait.clar"
clarity_version = 2
epoch = 2.5

[contracts.stakeflow-token]
path = "contracts/stakeflow-token.clar"
clarity_version = 2
epoch = 2.5

[contracts.stakeflow-nft]
path = "contracts/stakeflow-nft.clar"
clarity_version = 2
epoch = 2.5
depends_on = ["sip-009-trait"]

[contracts.stakeflow-staking]
path = "contracts/stakeflow-staking.clar"
clarity_version = 2
epoch = 2.5
depends_on = ["stakeflow-nft"]

[contracts.stakeflow-rewards]
path = "contracts/stakeflow-rewards.clar"
clarity_version = 2
epoch = 2.5
depends_on = ["stakeflow-staking", "stakeflow-token"]

[contracts.stakeflow-unstake]
path = "contracts/stakeflow-unstake.clar"
clarity_version = 2
epoch = 2.5
depends_on = ["stakeflow-staking", "stakeflow-rewards"]

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
